### ISSUE TITLE
Feature Request: Customize right-click on directory background

### ISSUE THREAD

**Issue by PrateekArya** [ikas-mc/ContextMenuForWindows11#44]
The app is really useful but it only allows to add an entry to right-click menu for files and folder. It can be a good idea to also allow the user to customize the background right-click context menu, i.e., the context menu which opens when a user right-clicks a the empty background of an already opened folder. For example, the context menu which you get when you right-click on the desktop.

**Comment by ikas-mc** [comment]
It's difficult....
Because the right-click menu api is called by windows...

There is currently only one special case, the desktop

https://github.com/ikas-mc/ContextMenuForWindows11/blob/d0c10a925d6601f41b94660c1ce56255d182d1bc/ContextMenuCustom/ContextMenuCustomHost/CustomExplorerCommand.cpp#L93

**Comment by cajazt** [comment]
@ikas-mc Would you consider implementing the desktop case? The app's useful for me since it allowed me to bring back some of the shortcuts I'd get on the desktop by default, like driver settings, but with the current version it also shows up whenever I right-click any other directory which isn't necessary. I'm not a programmer unfortunately so I don't know how to do that.

**Comment by ikas-mc** [comment]
@cajazt 
In order to solve folder-related bugs,
Currently a new implementation is used to get the folder path
see: https://github.com/microsoft/terminal/commit/5027c8031d009ff5d26032134ab1e70b0c91f587

Further testing is needed to see if specific folders can be identified
if it is possible,I will add a new matching option

**Comment by ikas-mc** [comment]
Add directory, desktop, and directory background matching
https://github.com/ikas-mc/ContextMenuForWindows11/releases/tag/5.0.0.0
