### ISSUE TITLE
Context menu is not created

### ISSUE THREAD

**Issue by TerminatedProcess** [ikas-mc/ContextMenuForWindows11#58]
I've read the wiki and tried creating a few context menus. One the default notepad example and the other is to execute a bat file of my own creation. Neither get's published to the context menu. I thought perhaps it was because I had the classic right-click menu registry fix so I restored it back to the Windows 11 default. But that didn't work either. At what point is the registry fixes published when using this app? Is it when I refresh the menu? I tried clicking the save icon first followed by refresh. Then quitting explorer and restarting explorer. Still nothing. Any ideas?

**Comment by FadeMind** [comment]
@lulMeow I installed app directly from Microsoft Store.

**Comment by FadeMind** [comment]
See `https://github.com/notepad-plus-plus/notepad-plus-plus/issues/10320#issuecomment-1287802821`

**Comment by vanontom** [comment]
I also see nothing from this app in my context menu, sadly. Perhaps this is due to recent updates to Windows Explorer (numerous in the past few months), since the latest release of this app?

- Windows 11 Pro (22H2, 22621.819)
- installed app directly from Windows Store
- in app clicked "refresh menu", have three entries (also yes in AppData folder)
- restarted Windows, restarted Explorer
- having issues with other context menu entries recently as well (WinRAR, until latest beta)
